import { Order } from "./types";

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "#12345",
    date: "2024-01-15",
    total: 150.0,
    status: "Shipped",
    products: [
      {
        id: "p1",
        name: "Premium Cotton T-Shirt",
        image: "/sampa-logo.png",
        color: "Blue",
        size: "M",
        quantity: 2,
        price: 75.0,
      },
    ],
    shippingAddress: {
      name: "Bayram Dikmen",
      street: "123 Main St",
      city: "Istanbul",
      postalCode: "34000",
      country: "Turkey",
    },
    paymentMethod: "Credit Card",
  },
  {
    id: "2",
    orderNumber: "#12346",
    date: "2024-02-20",
    total: 200.0,
    status: "Delivered",
    products: [
      {
        id: "p2",
        name: "Classic Jeans",
        image: "/sampa-logo.png",
        color: "Black",
        size: "32",
        quantity: 1,
        price: 120.0,
      },
      {
        id: "p3",
        name: "Leather Belt",
        image: "/sampa-logo.png",
        color: "Brown",
        quantity: 1,
        price: 80.0,
      },
    ],
    shippingAddress: {
      name: "Bayram Dikmen",
      street: "123 Main St",
      city: "Istanbul",
      postalCode: "34000",
      country: "Turkey",
    },
    paymentMethod: "PayPal",
  },
  {
    id: "3",
    orderNumber: "#12347",
    date: "2024-03-05",
    total: 75.0,
    status: "Processing",
    products: [
      {
        id: "p4",
        name: "Summer Hat",
        image: "/sampa-logo.png",
        color: "White",
        quantity: 1,
        price: 75.0,
      },
    ],
    shippingAddress: {
      name: "Bayram Dikmen",
      street: "123 Main St",
      city: "Istanbul",
      postalCode: "34000",
      country: "Turkey",
    },
    paymentMethod: "Credit Card",
  },
  {
    id: "4",
    orderNumber: "#12348",
    date: "2024-04-10",
    total: 300.0,
    status: "Delivered",
    products: [
      {
        id: "p5",
        name: "Winter Jacket",
        image: "/sampa-logo.png",
        color: "Navy",
        size: "L",
        quantity: 1,
        price: 300.0,
      },
    ],
    shippingAddress: {
      name: "Bayram Dikmen",
      street: "123 Main St",
      city: "Istanbul",
      postalCode: "34000",
      country: "Turkey",
    },
    paymentMethod: "Credit Card",
  },
  {
    id: "5",
    orderNumber: "#12349",
    date: "2024-05-12",
    total: 100.0,
    status: "Shipped",
    products: [
      {
        id: "p6",
        name: "Running Shoes",
        image: "/sampa-logo.png",
        color: "Red",
        size: "42",
        quantity: 1,
        price: 100.0,
      },
    ],
    shippingAddress: {
      name: "Bayram Dikmen",
      street: "123 Main St",
      city: "Istanbul",
      postalCode: "34000",
      country: "Turkey",
    },
    paymentMethod: "Debit Card",
  },
];

